CATALOG = [
    {
        "id": "synthetic-shirt-jacket-01",
        "title": "네이비 코튼 셔츠 재킷",
        "brand": "FITWISE LAB",
        "category": "outerwear",
        "price": 129000,
        "tags": {"워크숍", "출근", "미니멀", "네이비", "검은 슬랙스"},
        "quality": 0.86,
        "caution": "상품 실측은 합성 데이터이며 실제 구매에 사용할 수 없습니다.",
    },
    {
        "id": "synthetic-knit-02",
        "title": "차콜 메리노 크루넥 니트",
        "brand": "FITWISE LAB",
        "category": "top",
        "price": 89000,
        "tags": {"워크숍", "출근", "차콜", "단정", "검은 슬랙스"},
        "quality": 0.81,
        "caution": "소재와 세탁 정보는 프로토타입용 예시입니다.",
    },
    {
        "id": "synthetic-overshirt-03",
        "title": "올리브 텍스처 오버셔츠",
        "brand": "FITWISE LAB",
        "category": "top",
        "price": 118000,
        "tags": {"워크숍", "캐주얼", "올리브", "포인트", "검은 슬랙스"},
        "quality": 0.72,
        "caution": "오버핏 가정이므로 실제 사이즈표 확인이 필요합니다.",
    },
    {
        "id": "synthetic-blazer-04",
        "title": "블랙 소프트 블레이저",
        "brand": "FITWISE LAB",
        "category": "outerwear",
        "price": 189000,
        "tags": {"출근", "격식", "블랙", "미니멀"},
        "quality": 0.9,
        "caution": "현재 예산을 초과하면 추천 후보에서 제외됩니다.",
    },
]
